# Generated by Django 5.2.7 on 2025-10-07 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monthly_awards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date the job was invoiced')),
                ('utility_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('london_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cad_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nottingham_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contractor_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('psl_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Invoiced', 'Invoiced')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_jobs', to='monthly_awards.monthlyaward')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoiced Job',
                'verbose_name_plural': 'Invoiced Jobs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
