# Generated by Django 5.2.7 on 2025-10-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0001_initial'),
        ('monthly_awards', '0002_alter_monthlyaward_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedjob',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_jobs', to='monthly_awards.monthlyaward'),
        ),
    ]
