# Generated by Django 5.2.7 on 2025-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0003_alter_invoicedjob_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedjob',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this invoice', null=True),
        ),
    ]
