# Generated by Django 5.2.7 on 2025-10-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0004_invoicedjob_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedjob',
            old_name='nottingham_value',
            new_name='topo_value',
        ),
        migrations.RemoveField(
            model_name='invoicedjob',
            name='london_value',
        ),
    ]
