# Generated by Django 5.2.7 on 2025-10-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0005_rename_nottingham_value_invoicedjob_topo_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
