# Generated by Django 5.2.7 on 2025-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0006_alter_invoicedjob_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedjob',
            name='follow_up_status',
            field=models.CharField(choices=[('to_follow', 'To Follow'), ('followed_up', 'Followed Up'), ('n_a', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicedjob',
            name='followed_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
