# Generated by Django 5.2.7 on 2025-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiced_jobs', '0007_invoicedjob_follow_up_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedjob',
            name='follow_up_status',
            field=models.CharField(choices=[('n_a', 'N/A'), ('to_follow', 'To Follow'), ('followed_up', 'Followed Up')], default='N/A', max_length=20),
        ),
    ]
