# Generated by Django 5.2.7 on 2025-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0002_alter_salesenquiry_date_alter_salesenquiry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='client_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
