# Generated by Django 5.2.7 on 2025-10-06 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0003_alter_salesenquiry_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='client',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='client_contact',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
