# Generated by Django 5.2.7 on 2025-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0004_alter_salesenquiry_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='job_number',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
