# Generated by Django 5.2.7 on 2025-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0005_alter_salesenquiry_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='job_number',
            field=models.CharField(max_length=20),
        ),
    ]
