# Generated by Django 5.2.7 on 2025-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0006_alter_salesenquiry_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesenquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
