# Generated by Django 5.2.7 on 2025-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0008_alter_salesenquiry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenquiry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
