# Generated by Django 5.2.7 on 2025-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0009_salesenquiry_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenquiry',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
