# Generated by Django 5.2.7 on 2025-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0010_salesenquiry_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesenquiry',
            name='other_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='feedback',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Timeframe', 'Timeframe'), ('Capability', 'Capability'), ('Other', 'Other')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='salesenquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Awarded', 'Awarded'), ('Not_Quoted', 'Not Quoted')], default='Pending', max_length=10),
        ),
    ]
